### ISSUE TITLE
useKey should be able to accept a single key as first argument

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#117]
**Is your feature request related to a problem? Please describe.**
useKey currently accepts only an array of keys. We need to be able to accept a single value as argument.

**Describe the solution you'd like**
Right now for a single key we need to use`useKey(['Enter'],...)`
We should be able to do `useKey('Enter', ...)`

**Comment by simbathesailor** [comment]
Hi @imbhargav5 ,

Let's discuss this, 

1. We need to handle also the string type as the first arguments.
2. We need to handle the scenario when passing the inValid key name, should warn the user . or should we not?. Because I checked the code doesIdentifierMatchKeyboardEvent in the shared folder. It will not invalidate it but will not run when passing invalid keys

Thoughts?

**Comment by imbhargav5** [comment]
Yeah I don’t think we need to invalidate. We should leave it to the user. Too much Dev work for too little result.

**Comment by imbhargav5** [comment]
But string type as first argument would be really intuitive.

**Comment by imbhargav5** [comment]
This is fixed with this commit. 22b14b43c3a3fe1f33936e2588c73242543d1014
