### ISSUE TITLE
useLocalStorageState overrides local-storage item

### ISSUE THREAD

**Issue by sch-28** [imbhargav5/rooks#1720]
Hello!

I noticed that the hook **useLocalStorageState** overrides local-storage items whenever the key from an **already initialised useLocalStorageState** is changed. Changing the key triggers the `saveValueToLocalStorage` function with the new key causing an override with no regard of the previous value behind that key.

Is this intentional?

**Comment by sch-28** [comment]
I created a test and added an attempt to fix the issue

**Comment by imbhargav5** [comment]
@sch-28  This is actually a very interesting case. Changing the key itself hmmm. So the behaviour isn't intentional but it is a strange use case. Definitely something we didn't think about.

Could you explain your particular use case again? Mainly, why the key itself needs to change? And perhaps keeping separate useLocalstorageState for a different key makes sense ?

**Comment by sch-28** [comment]
So it actually came up, because the key was an id that was fetched asynchronously. And for the time it was available i used a default key. But after the id was fetched and the state updated itself the item stored behind the id was suddenly overwritten by the default value.. 
I couldnt find a way to conditionally use the hook to wait for the id to arrive :/

**Comment by imbhargav5** [comment]
@sch-28 Perhaps the component containing the hook can be conditionally rendered instead? I am suggesting an alternative way to use this hook because I am concerned that dabbling with keys might open up a can of worms that are very difficult to fix and the test cases needed for this will be at another level entirely. 

Would love for you to contribute to any issue in this project, but I am hesitant to merge any changes where the key itself changes in this hook.

**Comment by sch-28** [comment]
Hm, while this would work i am not sure if I like this approach. I can however understand that your standpoint on this. I am not sure either; the change might create unforeseen side effects.

**Comment by imbhargav5** [comment]
@sch-28 Yeah I am slightly worried about breaking the most common use case for this one while fixing the issue you pointed out. Thanks for reaching out! Closing this issue for now. Have a good day!
