### ISSUE TITLE
useLazyImage

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#22]
**Is your feature request related to a problem? Please describe.**
We need a hook to lazily load imgs

**Describe the solution you'd like**
```jsx

function Profile(){
   const [src, isLoading, isVisible] = useLazyImage(src, fallbackSrc, visibilityOptions)
   return <img src={src} />
}
```

It should internally use `@rooks/use-visibility-sensor`

**Describe alternatives you've considered**
We have been using react-lazy-image and react-lazy-progressive-image and it's about time we have a hook!

**Comment by JayaKrishnaNamburu** [comment]
Hi, @imbhargav5 how about giving a try for [lazysizes](https://github.com/aFarkas/lazysizes) it's simple and around 3.5kb in size, here is the [example](https://jayakrishnanamburu.github.io/travel/) which I used for implementing. How about building a wrapper which uses this under the hood.

**Comment by imbhargav5** [comment]
Hmm, aren't they two different things? One is about sizes, the other is about loading an image only when the component is in the viewport. Am I missing something?

**Comment by JayaKrishnaNamburu** [comment]
No, actually the name is a little mis-leading this is written in plain js, which automatically sets the src vakue of image when the user scrolls and the image comes to the view port, you check the network tab by loading the example i shared.

**Comment by simbathesailor** [comment]
Hey @imbhargav5. I want to take a hit at this. Can I go ahead and take this issue?. I will discuss the approach when I have done some kind of homework around it. Thanks

**Comment by imbhargav5** [comment]
Sure please do. Sorry I responded late. Fell sick and was away from internet for a while.

**Comment by simbathesailor** [comment]
@imbhargav5 It's ok man, take care !!. While implementing the useLazyImage I checked the useVisibility hook(so that i can make use of it). There were some issues which I figured out with the approach used in it:

1.Right not it is based on getBoundingClientRect(). which runs on main thread can cause make the scrolling sluggish, if there are many event listener attached. Hence thought of suggesting , IntersectionObserver which  doesnot runs on main thread.
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API.
https://caniuse.com/#search=intersectionObserver
Polyfill is also available: https://github.com/w3c/IntersectionObserver


2. there is no way to remove the event listener right now in useVisibility. As for the images which once gets downloaded , we should be able to drop off the event listeners for them.

What are your thoughts about it ? Can we make a new issue , where we can discuss the implementation of useVisibility using interSectionObserver if required. Or a new hook altogether.

**Comment by imbhargav5** [comment]
Nice. IntersectionObserver sounds good. Go ahead man!

**Comment by ranjith29h** [comment]
@imbhargav5 
Intersection Observer call back runs in the **main thread**.
![IntersectionObserver](https://user-images.githubusercontent.com/12975992/59329721-32ed1400-8d0d-11e9-8c83-efea0a03bbf4.png)

[here](https://developers.google.com/web/updates/2016/04/intersectionobserver)

**Comment by simbathesailor** [comment]
@ranjith29h 
Yes you right, thanks for correcting me. I just misinterpret the mdn docs.The callback runs in the main thread. The reason for the jank behavior when using getBoundingClientRect() will cause re-layout of the whole page which ultimately a synchronous task hence the jank behaviour. Nice read .
IntersectionObservers doesn't cause re-layout hence performant!!

**Comment by ranjith29h** [comment]
@simbathesailor The below link will helpful 
https://addyosmani.com/blog/lazy-loading/

**Comment by simbathesailor** [comment]
@imbhargav5 I did the useLazyLoadImage first cut. There are quite some things which are pending. 

have a look at it and give me feedback if any. APIs are not final, may change in future. here is the sandbox link:

https://codesandbox.io/s/uselazyimage-mof97

**Comment by imbhargav5** [comment]
Sure go ahead. Let's try to get in useIntersectionObserver for `3.4.0` and take `useLazyImage` in `3.5.0` from there.

**Comment by simbathesailor** [comment]
> Sure go ahead. Let's try to get in `useIntersectionObserver` for `3.4.0` and take `useLazyImage` in `3.5.0` from there.

Sounds Perfect!!
