### ISSUE TITLE
useBoundingclientrect do not update

### ISSUE THREAD

**Issue by Chetan11-dev** [imbhargav5/rooks#512]
in case you update styles via dom useBoundingclientrect will not update while it actually should
```
const node = document.createElement("style")
node.appendChild(document.createTextNode(".element{width:500px}"))
```
Reason: MutationObserver(used in hook) does not fire in such scenario 
Solution: use ResizeObserver instead 
Example
```
const HoverBoxResize: FC<{id:string}> = ({ id }) => {
    const [state, setstate] = useState<null | DOMRect>(null);

    useEffect(() => {
        const el = document.getElementById(id);
        if (el) {
            const observer = new ResizeObserver(() => {
                setstate(el.getBoundingClientRect());
            });
            console.log("connected" + id);
            observer.observe(el);
            return () => {
                console.log("disconnected");
                observer.disconnect();
            };
        }
    }, [id]);

    console.log(state)
    return null
};

```
Great efforts indeed. Love from India.

**Comment by imbhargav5** [comment]
@Chetan11-dev You are right. A `ResizeObserver` PR is in the works. We will update the `useBoundingClientRect` hooks soon.

**Comment by phmngocnghia** [comment]
Are the PR working in progress? I would like to contribute

**Comment by seanblonien** [comment]
@phmngocnghia hm, seems like this is still very relevant and it was never actually completed. I don't see `ResizeObserver` usage anywhere in the code and am running into some bugs because of it

I'll probably be using [use-resize-observer](https://github.com/ZeeCoder/use-resize-observer#readme) instead until this functionality exists within `rooks`

Not very sure what the standards are for open source projects, but I'd just "copy" this package's implementation and do some light refactoring to "make it in the style of rooks"
