### ISSUE TITLE
NextJS / SSR support

### ISSUE THREAD

**Issue by PascalPixel** [imbhargav5/rooks#559]
`window` is not defined during SSR, defensive programming and fallback would make it work.

(Use `useWindowScrollPosition` with NextJS during SSR to see error)

**Comment by qiweiii** [comment]
@imbhargav5 I am not familiar with next.js and ssr, could you take a look first? I may need more time to learn.

**Comment by PascalPixel** [comment]
NextJS uses React's `ReactDOMServer` to render the HTML in Node. 

There is no `window` object in Node. (`globalThis` will eventually patch this...).

As a result any use of `window` needs to use `typeof window !== 'undefined'` with a fallback. :) Hope this helps!

**Comment by danielortiz** [comment]
if that helps anyone, I've done this for now while this doesn't get fixed
```
import { useOnWindowScroll as useOnWindowScrollOriginal } from 'rooks'
const useOnWindowScroll = typeof window === 'object' ? useOnWindowScrollOriginal : () => {}
```

**Comment by ackl** [comment]
this is implemented correctly in some places but not others

e.g. https://github.com/imbhargav5/rooks/blame/main/src/hooks/useWindowEventListener.ts

has a `  if (typeof window !== 'undefined')` check before calling `useGlobalObjectEventListener` (note that the guard in `useGlobalObjectEventListener` is not enough, since to call this method we need to pass the globalObject arg (window or document) which is not defined server side)

but https://github.com/imbhargav5/rooks/blob/main/src/hooks/useOnWindowScroll.ts https://github.com/imbhargav5/rooks/blob/main/src/hooks/useOnWindowResize.ts do not

**Comment by qiweiii** [comment]
A PR is working in progress

**Comment by pingustar** [comment]
@qiweiii any update on this?

**Comment by KasperAndersson** [comment]
@pingustar It's stucked here https://github.com/imbhargav5/rooks/pull/564

**Comment by mindyourlifeguide** [comment]
Hi! useOnWindowScroll and  useOnWindowResize not support SSR.
![image](https://user-images.githubusercontent.com/35348648/175271100-f6ea6eeb-db16-48b4-b5e2-28be4469d6b2.png)

**Comment by sgehrman** [comment]
Doesnt' work in     "rooks": "^6.4.1",

**Comment by PascalPixel** [comment]
Can you override `window` in your typescript and say it might be undefined?

Or do this and use `win` everywhere?
```const win = typeof window !== "undefined" ? window : undefined;```
