### ISSUE TITLE
useInterval hooks does not work as expected in certain scenarios.

### ISSUE THREAD

**Issue by simbathesailor** [imbhargav5/rooks#60]
**Describe the bug**
So I was trying to understand hooks patterns where I tried to use useInterval hooks from rooks :). The callback is not having access to updated value. hence not updating the value in the component it uses

**To Reproduce**
1. This is the codepen with using existing useInterval  
https://codepen.io/stack26/pen/LvRaWe?editors=1111

2. This is the codepen where I sort of fixed it by passing dependency.
https://codepen.io/stack26/pen/MRjPJx?editors=1011

If it's sound legit, let me know. I will complete it according to this project, adding test cases, upadating type definitions and will raise a pull request for it. This will be my first opensource contribution :).

**Comment by imbhargav5** [comment]
Hey @simbathesailor True. This is an issue and it has been fixed in the dev branch. I haven't released it  to `latest`yet. But it will be out shortly. Meanly please try using using the `alpha` version `npm i @rooks/use-interval@alpha`. This issue is solved in that branch.

Please let me know if it worked for you!

**Comment by simbathesailor** [comment]
Yes It works, Thanks. the solution is much cleaner in alpha release. So you used useRef for persisting the callback hence the scope hence the correct updated value. Am i right ?

**Comment by imbhargav5** [comment]
Yes that's right. :) It was contributed in a PR after an implementation example for this was given by @gaearon.
